version: '3.3'
services:

  els:
    build: ./els
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false

  lfr:
    image: "liferay/liferay-portal:7.1.0-ga1-1.1"
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - "ELS_ADDRESS=els:9300"
      - "LIFERAY_ELS_PERIOD_ADDRESS=els:9300"
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_HTTP_PERIOD_PORT=8080
    volumes:
      - type: bind
        source: ./lfr
        target: /docker-init.d/
    depends_on:
      - els